### ISSUE TITLE
use shabnam font

### ISSUE THREAD

**Issue by hosseinse1919** [sadra/middle-east#4]
hi ..  i think it is better to use shabnam font

it is very awesome font to reading and writing

**Comment by sadra** [comment]
> hi .. i think it is better to use shabnam font 
> it is very awesome font to reading and writing

Dear @hosseinse1919, thank you for your comment. We need to use standard and general fonts in the project because there are many **Arabic** and **Hebrew** users who use Typora that the **Shabnam** wouldn't be comfortable for that users.

But, you can add the Shabnam by yourself in **Tyopra**. Just download the theme, put your fonts in the font folder, modify the `CSS` and replace the Vazir's font with the Shabnam one.

Just let me know if you have any issue doing it. :)

**Comment by hosseinse1919** [comment]
it is ok but shabnam is based on vazir 

and i did that before .
